### ISSUE TITLE
should terminate immediately if forbidden char in target (e.g. 1)

### ISSUE THREAD

**Issue by 1m1-github** [peterkrull/algo-vanity-rs#1]

**Comment by peterkrull** [comment]
You are right. I had actually implemented this but got caught up in exams and forgot to push it. I have [pushed the change](https://github.com/peterkrull/algo-vanity-rs/commit/883e6871407fd7767d91330bf2630c282331731b) now if compile yourself. I will compile binaries and release them in a bit.

**Comment by peterkrull** [comment]
[Updated binaries are live](https://github.com/peterkrull/algo-vanity-rs/releases/tag/v0.2)
